server:
  port: 9040
spring:
  profiles:
    include: common
    active: dev
  servlet:
    multipart:
      # 上传文件最大大小
      max-file-size: 5MB

#novel:
#  file:
#    # 文件上传配置
#    upload:
#      # 上传路径
#      path: /Users/cheunry/Project/Data/turtle_website/upload

management:
  # 端点启用配置
  endpoint:
    logfile:
      # 启用返回日志文件内容的端点
      enabled: true
      # 外部日志文件路径
      external-file: logs/novel-resource-service.log

--- #---------------------存储桶配置---------------------------
tencent:
  cos:
    secret-id: ${TENCENT_COS_SECRET_ID}
    secret-key: ${TENCENT_COS_SECRET_KEY}
    region: ${TENCENT_COS_REGION}
    bucket-name: ${TENCENT_COS_BUCKET_NAME}
    base-url: https://${tencent.cos.bucket-name}.cos.${tencent.cos.region}.myqcloud.com